name: Build EXE with PyInstaller

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller wikipedia requests pymorphy2 bs4 pyttsx3

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --windowed --icon=reika/Rei.ico --add-data "reika/rei_data;rei_data" --add-data "reika/rei_games;rei_games" reika/rei.pyw

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: rei-windows-exe
          path: dist/
